---
title: "Cleaning"
author: "Saatvik Kher"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(broom)
theme_set(theme_minimal())
```

# Imports

```{r}
primary <- read_excel("WeeklySummary_COVID19_VE_Studies_02Feb2023_0.xlsx", 
    sheet = "Primary Series Studies")

booster <- read_excel("WeeklySummary_COVID19_VE_Studies_02Feb2023_0.xlsx", 
    sheet = "Booster Studies")

booster <- booster %>% select(-`...22`, -`...23`, -`...24`, -`...25`)
```

# Cleaning and preliminary analysis

VE distribution for Pfizer and Moderna

```{r}
primary %>%
  filter(str_detect(vaccine, "Pfizer"),
         VE > 0) %>%
  ggplot(aes(VE)) +
  geom_density() +
  ggtitle("Pfizer")
```

```{r}
primary %>%
  filter(str_detect(vaccine, "Moderna"),
         VE > 0) %>%
  ggplot(aes(VE)) +
  geom_density() +
  ggtitle("Moderna")
```

Similar distributions for both! That's good. Let's try to bin it by dose day


```{r}
primary %>%
  filter(`first author` == "Lin", str_detect(vaccine, "Pfizer"), `study ID` == 326) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL)) %>%
  mutate(timing_of_dose_days = case_when(
    str_detect(timing_of_dose_days, "months") ~ 30 * parse_number(timing_of_dose_days),
    str_detect(timing_of_dose_days, "weeks") & !str_detect(timing_of_dose_days, "to") & !str_detect(timing_of_dose_days, "-") ~ 7*parse_number(timing_of_dose_days)
    )
  ) %>%
  ggplot(aes(timing_of_dose_days, VE, color = outcome_category)) +
  geom_point() +
  geom_line() +
  geom_ribbon(aes(ymin = LCL, ymax = UCL, group = outcome_category, fill=outcome_category), alpha = 0.2)
```

```{r}
primary %>%
  filter(`first author` == "Lin", str_detect(vaccine, "Moderna"), `study ID` == 326) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL)) %>%
  mutate(timing_of_dose_days = case_when(
    str_detect(timing_of_dose_days, "months") ~ 30 * parse_number(timing_of_dose_days),
    str_detect(timing_of_dose_days, "weeks") & !str_detect(timing_of_dose_days, "to") & !str_detect(timing_of_dose_days, "-") ~ 7*parse_number(timing_of_dose_days)
    )
  ) %>%
  ggplot(aes(timing_of_dose_days, VE, color = outcome_category)) +
  geom_point() +
  geom_smooth(aes(group=outcome_category), se=FALSE) +
  geom_ribbon(aes(ymin = LCL, ymax = UCL, group = outcome_category, fill=outcome_category), alpha = 0.2)
```

```{r}
primary %>%
  filter(`first author` == "Lin", str_detect(vaccine, "Janssen"), `study ID` == 326) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL)) %>%
  mutate(timing_of_dose_days = case_when(
    str_detect(timing_of_dose_days, "months") ~ 30 * parse_number(timing_of_dose_days),
    str_detect(timing_of_dose_days, "weeks") & !str_detect(timing_of_dose_days, "to") & !str_detect(timing_of_dose_days, "-") ~ 7*parse_number(timing_of_dose_days)
    )
  ) %>%
  ggplot(aes(timing_of_dose_days, VE, color = outcome_category)) +
  geom_point() +
  geom_line() +
  geom_ribbon(aes(ymin = LCL, ymax = UCL, group = outcome_category, fill=outcome_category), alpha = 0.2)
```



```{r}
primary %>%
  filter(`study ID` == 326) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL)) %>%
  mutate(timing_of_dose_days = case_when(
    str_detect(timing_of_dose_days, "months") ~ 30 * parse_number(timing_of_dose_days),
    str_detect(timing_of_dose_days, "weeks") & !str_detect(timing_of_dose_days, "to") & !str_detect(timing_of_dose_days, "-") ~ 7*parse_number(timing_of_dose_days)
    ),
    vaccine = case_when(
      str_detect(vaccine, "Pfizer") ~ "Pfizer",
      str_detect(vaccine, "Moderna") ~ "Moderna",
      str_detect(vaccine, "Janssen") ~ "Janssen"
    )
  ) %>%
  select(timing_of_dose_days, VE, LCL, UCL, vaccine, outcome_category) %>%
  ggplot(aes(timing_of_dose_days, VE, color = vaccine)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_grid(~outcome_category)
```




# Boosters?? 

```{r, warning=FALSE}
booster %>%
  filter(str_detect(`booster vaccine`, "Pfizer"), 
         outcome_category == "infection") %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL)) %>%
  mutate(timing_of_dose_days = case_when(
    str_detect(timing_of_dose_days, "month") ~ 30 * parse_number(timing_of_dose_days),
    str_detect(timing_of_dose_days, "weeks") & !str_detect(timing_of_dose_days, "to") & !str_detect(timing_of_dose_days, "-") ~ 7*parse_number(timing_of_dose_days)
    )
  ) %>%
  ggplot(aes(timing_of_dose_days, VE, color = outcome_category)) +
  geom_point() +
  geom_smooth()
```














# XH cleaned data explore


```{r, warning=FALSE}
primaryxh <- (read_csv("../xh_temp_folder/cleaned_ve_data_no_open_interval.csv"))[-1]

filtered <- primaryxh %>%
  filter(vaccine %in% c("Pfizer", "Moderna", "Janssen"),
         VE > 0,
         days_since_first_dose < 400,
         outcome_category == "infection",
         (time_sup - time_inf) < 42
         ) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL), `study ID` = as.factor(`study ID`)) %>%
  group_by(`study ID`) %>%
  summarise(max = max(days_since_first_dose)) %>% 
  filter(max > 100) %>%
  pull(`study ID`)




primaryxh %>%
  filter(vaccine %in% c("Pfizer", "Moderna", "Janssen"),
         VE > 0,
         days_since_first_dose < 400,
         outcome_category == "infection",
         (time_sup - time_inf) < 42,
         `study ID` %in% filtered
         ) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL), `study ID` = as.factor(`study ID`)) %>%
  ggplot(aes(days_since_first_dose, VE, color = `study ID`)) +
  geom_point() +
  geom_line() +
  facet_grid(~vaccine)
```

```{r}
primaryxh %>%
  filter(vaccine %in% c("Pfizer"),
         VE > 0,
         days_since_first_dose < 400,
         outcome_category == "infection",
         (time_sup - time_inf) < 42,
         `study ID` %in% filtered
         ) %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL), `study ID` = as.factor(`study ID`)) %>%
  lm(VE~days_since_first_dose, data = .) %>%
  glance()
```



```{r}
primary %>%
  filter(`first author` == "Lin", 
         str_detect(vaccine, "Pfizer"), 
         `study ID` == 326,
         outcome_category == "infection") %>%
  mutate(LCL = as.numeric(LCL), UCL = as.numeric(UCL)) %>%
  mutate(timing_of_dose_days = case_when(
    str_detect(timing_of_dose_days, "months") ~ 30 * parse_number(timing_of_dose_days),
    str_detect(timing_of_dose_days, "weeks") & !str_detect(timing_of_dose_days, "to") & !str_detect(timing_of_dose_days, "-") ~ 7*parse_number(timing_of_dose_days)
    )
  ) %>%
  select(timing_of_dose_days, VE, LCL, UCL) %>%
  ggplot(aes(timing_of_dose_days, VE)) +
  geom_point() +
  geom_line() +
  geom_ribbon(aes(ymin = LCL, ymax = UCL), alpha = 0.2)
```

```{r}
primaryxh %>%
  filter(`study ID` == 318)
```

